name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change this if you want to deploy from a different branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '20.11.0'  # Change this to the Node.js version you use

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Build Vite app
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Production files
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: Production files
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 
        with:
          github_token: ${{ secrets.Token }}
          publish_dir: ./dist
